In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

In [4]:
path ="~/data/crude_oil_price/"
# df = pd.read_excel("../../data/crude_oil_price/11_01_2017_11_01_2018.xlsx",sheet_name=None)
# # df = pd.read_csv("../../data/crude_oil_price/11_01_2017_11_01_2018.csv")
# df = df['11_01_2017_11_01_2018']
df = pd.read_csv("../../data/crude_oil_price/20131019_20181119.csv")
df = df.rename({"日期":"date","最新":"latest","開市":"open","高":"high","低":"low","成交量":"quantity","更改%":"percentage"}, axis='columns')
df['percentage'] = [float(x[:-1]) for x in df['percentage']]
opens=df.open
closes=df.latest
highs=df.high
lows=df.low
df.date = pd.to_datetime(df.date, format='%Y年%m月%d日')
df.sort_values(by="date",ascending=True,inplace=True)
std = df['percentage'].std()
avg = df['percentage'].mean()
print("平均:",avg,"標準差:",std)

平均: -0.0194614809274 標準差: 2.17710937913

In [5]:
# df['important'] = "no"
up_news = df[df['percentage']>avg+std]
down_news = df[df['percentage']<avg-std]

## std_change

In [15]:
days_before = 5
days_after = 2
std_before = df['latest'].rolling(days_before).std().shift(1)
std_after = df['latest'].rolling(days_after).std().shift(-1*(days_after))
effective_news_date = df[std_after>std_before]

In [51]:
effective_news_date.index = pd.DatetimeIndex(effective_news_date.date)

In [54]:
effective_news_date["2017-12":]

                 date  latest   open   high    low quantity  percentage
date
2017-12-05 2017-12-05   57.62  57.48  57.92  57.08  499.25K        0.26
2017-12-11 2017-12-11   57.99  57.25  58.08  56.91  606.72K        1.10
2017-12-25 2017-12-25   58.59  58.41  58.62  58.38        -        0.21
2018-01-02 2018-01-02   60.37  60.20  60.74  60.10  510.31K        0.22
2018-01-08 2018-01-08   61.73  61.61  61.97  61.34  616.47K        0.47
2018-01-09 2018-01-09   62.96  61.92  63.48  61.80  844.72K        1.99
2018-01-15 2018-01-15   64.73  64.28  64.89  64.11        -        0.70
2018-01-22 2018-01-22   63.49  63.61  64.14  63.17   40.06K        0.19
2018-01-23 2018-01-23   64.47  63.88  64.88  63.70  662.46K        1.54
2018-01-25 2018-01-25   65.51  65.88  66.66  65.08  771.76K       -0.15
2018-01-29 2018-01-29   65.56  66.18  66.46  64.98  656.17K       -0.88
2018-02-06 2018-02-06   63.39  63.43  64.29  63.12  797.81K       -1.18
2018-02-08 2018-02-08   61.15  61.70  62.09  60.27  929.58K       -1.04
2018-02-13 2018-02-13   59.19  59.35  59.73  58.39  580.60K       -0.17
2018-02-27 2018-02-27   63.01  64.06  64.08  62.64  562.67K       -1.41
2018-02-28 2018-02-28   61.64  62.79  63.44  61.36  768.41K       -2.17
2018-03-02 2018-03-02   61.25  61.34  61.60  60.13  613.51K        0.43
2018-03-06 2018-03-06   62.60  62.58  63.28  62.17  634.95K        0.05
2018-03-08 2018-03-08   60.12  61.33  61.40  59.95  720.51K       -1.68
2018-03-19 2018-03-19   62.06  62.23  62.35  61.36  115.96K       -0.45
2018-03-20 2018-03-20   63.40  62.10  63.81  62.08   36.06K        2.16
2018-03-22 2018-03-22   64.30  65.50  65.74  64.14  689.17K       -1.33
2018-03-29 2018-03-29   64.94  64.69  65.26  64.16  562.82K        0.87
2018-04-05 2018-04-05   63.54  63.60  64.12  63.07  588.60K        0.27
2018-04-06 2018-04-06   62.06  63.70  63.79  61.81  753.26K       -2.33
2018-04-09 2018-04-09   63.42  62.00  63.61  61.93  655.83K        2.19
2018-04-13 2018-04-13   67.39  67.18  67.76  66.70  624.20K        0.48
2018-04-17 2018-04-17   66.52  66.42  66.75  65.56  486.08K        0.45
2018-04-30 2018-04-30   68.57  68.15  69.34  67.17  755.19K        0.69
2018-05-01 2018-05-01   67.25  68.56  68.90  66.85  694.77K       -1.93
...               ...     ...    ...    ...    ...      ...         ...
2018-05-25 2018-05-25   67.88  70.65  70.80  67.42  955.35K       -4.00
2018-05-29 2018-05-29   66.73  67.55  67.55  65.80    1.06M       -0.48
2018-05-30 2018-05-30   68.21  66.85  68.67  66.35  726.89K        2.22
2018-06-06 2018-06-06   64.73  65.51  65.96  64.27  708.83K       -1.21
2018-06-14 2018-06-14   66.89  66.62  67.16  66.36  460.17K        0.38
2018-06-18 2018-06-18   65.85  64.40  65.98  63.59  218.93K        1.21
2018-06-19 2018-06-19   65.07  65.82  65.90  64.39  122.65K       -1.18
2018-06-20 2018-06-20   66.22  65.11  66.53  65.01   30.65K        1.77
2018-06-21 2018-06-21   65.54  65.34  66.22  64.34  760.72K       -1.03
2018-06-25 2018-06-25   68.08  68.75  69.44  67.78  816.21K       -0.73
2018-06-26 2018-06-26   70.53  68.21  70.91  67.72  848.54K        3.60
2018-07-10 2018-07-10   74.11  74.04  74.70  73.65  586.83K        0.35
2018-07-13 2018-07-13   71.01  70.38  71.66  69.84  530.28K        0.97
2018-07-27 2018-07-27   68.69  69.58  69.77  68.26  460.45K       -1.32
2018-08-07 2018-08-07   69.17  68.90  69.83  68.81  485.03K        0.23
2018-08-14 2018-08-14   67.04  67.42  68.37  66.58  538.48K       -0.24
2018-08-21 2018-08-21   67.35  66.62  68.10  66.52   27.15K        1.38
2018-09-04 2018-09-04   69.87  69.89  71.40  69.08  785.98K       -0.36
2018-09-10 2018-09-10   67.54  67.82  68.52  67.33  571.17K       -0.31
2018-09-11 2018-09-11   69.25  67.53  70.01  67.48  676.87K        2.53
2018-09-12 2018-09-12   70.37  69.89  71.26  69.50  800.54K        1.62
2018-09-18 2018-09-18   69.85  68.80  70.42  68.53  234.20K        1.36
2018-09-28 2018-09-28   73.25  72.18  73.73  71.88  544.05K        1.57
2018-10-02 2018-10-02   75.23  75.42  75.91  74.93  463.62K       -0.09
2018-10-03 2018-10-03   76.41  75.12  76.90  74.30  698.82K        1.57
2018-10-16 2018-10-16   71.92  71.72  72.29  71.02  535.00K        0.20
2018-10-17 2018-10-17   69.75  72.17  72.43  69.43  651.58K       -3.02
2018-10-22 2018-10-22   69.17  69.41  69.65  68.27   27.42K        0.07
2018-11-05 2018-11-05   63.10  62.99  64.14  62.52  609.13K       -0.06
2018-11-12 2018-11-12   59.93  60.70  61.28  58.68  806.22K       -0.43

[66 rows x 7 columns]

## pct_change

In [35]:
latest_pct_change=df['latest'].pct_change(2).shift(-2)
latest_pct_change_mean=latest_pct_change.mean()
latest_pct_change_std=latest_pct_change.std()

t=.8
df['two_day_percentage']=latest_pct_change
effective_news_date=df.loc[latest_pct_change>latest_pct_change_mean+t*latest_pct_change_std].set_index('date')
# effective_news_date['two_day_percentage']=latest_pct_change.values
print(len(effective_news_date))
effective_news_date["2018"].head()

211

,latest,open,high,low,quantity,percentage,two_day_percentage
date,,,,,,,
2018-01-02,60.37,60.20,60.74,60.10,510.31K,0.22,0.027166
2018-01-05,61.44,61.90,62.04,61.09,563.04K,-0.92,0.024740
2018-01-08,61.73,61.61,61.97,61.34,616.47K,0.47,0.029807
2018-01-22,63.49,63.61,64.14,63.17,40.06K,0.19,0.033391
2018-02-13,59.19,59.35,59.73,58.39,580.60K,-0.17,0.036324

## Write to csv

In [47]:
effective_news_date.to_csv("../../data/crude_oil_price/effective_news_date_days_before_and_after.csv")

## Plot

In [1]:
# plotly 
import plotly as py
import plotly.graph_objs as go
%load_ext autoreload
%autoreload 2

# offline plot  
# 因為如果寫成func去調用plotly會無法出現，所以只好用offline的方式。
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

In [2]:
# Create traces
trace1 = go.Scatter(
    x = df['date'],
    y = df['percentage'],
    mode = 'lines+markers',
    name = 'lines+markers'
)
trace2 = go.Scatter(
    x = df['date'],
    y = df['open'],
    mode = 'lines+markers',
    name = 'lines+markers'
)

data = [trace1,trace2]
iplot(data, filename='scatter-mode')

NameError: name 'df' is not defined